name: Snyk SCA Scan

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: trufflehog scanning
      continue-on-error: false
      run: |
       docker run -i -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --repo https://github.com/swathisenthilkumar/webgoat --only-verified --json > result.json
    - name: Archive Scan results
      uses: actions/upload-artifact@v2
      with:
          name: scan-report
          path: result.json
