name: Snyk SCA Scan

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  trufflehog:
    permissions:
      contents: read 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: trufflehogscanning
      id: scan
      continue-on-error: true
      run: |
         docker run -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --only-verified --fail
    - name: trufflehogcondition
      id: condition
         if :steps.scan.outcome != 'success' 
      run: |
          curl -H 'Content-Type: application/json' -d ' {"text": "Your application has secrets" }'  $(webhook)
          exit 1
          else
            echo "check"
            curl -H 'Content-Type: application/json' -d ' {"text": "Your application has no secrets" }'  $(webhook)
          fi
          continueOnError: true
      # docker run -i -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --repo https://swathisenthilkumar:${{ secrets.Git_hub_token }}@github.com/swathisenthilkumar/webgoat.git  --no-verification  --fail 
  #  - name: Archive Scan results
  #    uses: actions/upload-artifact@v2
  #    with:
   #       name: scan-report
   #       path: result.json
